### ISSUE TITLE
Reddit - Stickied Posts?

### ISSUE THREAD

**Issue by ginglis13** [wtheisen/commandChan#3]
Should the reddit jawn skip stickied posts on each subreddit or include those?

Also would it be cool to add an option to the config file for the default site i.e. reddit or chan

**Comment by wtheisen** [comment]
I don't really use reddit what does @sambattalio think about this?

**Comment by sambattalio** [comment]
I personally don't ever look at stickied posts. Aren't they mostly subreddit rules and stuff? If you wanna add it, I don't see a harm in having it because some subreddits use it for like events (like feedback friday or some crap like that). I am sure it'd be pretty easy with the api though to snag them.

**Comment by ginglis13** [comment]
yea that's what i'm thinkin, stickies are normally announcements/rules. Right now it is not filtering out stickied posts. We just have to add 

```if data['stickied']:
                continue
```

to not include them if we don't want to include them. But nothing needs to be done if you guys still want them in there, maybe we could color code them if they are stickied??

**Comment by wtheisen** [comment]
I would say hide them by default and then add a command to unhide them

**Comment by sambattalio** [comment]
[chad](http://www.chadpaste.com/images/cqv.jpg) has spoken
